name: Auto commit Scheduled

on:
  schedule:
    
    - cron: "0 * * * *"
  
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      
      - name: Modify LAST_UPDATED file
        run: |
          # Perintah ini akan membuat/mengubah file LAST_UPDATED dengan tanggal saat ini
          echo "Last updated on $(date)" > LAST_UPDATED

      
      - name: Commit and Push changes
        run: |
          git config --local user.email "maarzsyena@gmail.com"
          git config --local user.name "andidelouise"
          git add -A
          
          # Cek apakah ada perubahan, jika ada baru commit
          if ! git diff --staged --quiet; then
            git commit -m "chore: auto update activity"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
          force: true
